DROP SCHEMA IF EXISTS master0;
DROP SCHEMA IF EXISTS master1;
DROP SCHEMA IF EXISTS master0slave0;
DROP SCHEMA IF EXISTS master0slave1;
DROP SCHEMA IF EXISTS master1slave0;
DROP SCHEMA IF EXISTS master1slave1;

CREATE SCHEMA IF NOT EXISTS master0;
CREATE SCHEMA IF NOT EXISTS master1;
CREATE SCHEMA IF NOT EXISTS master0slave0;
CREATE SCHEMA IF NOT EXISTS master0slave1;
CREATE SCHEMA IF NOT EXISTS master1slave0;
CREATE SCHEMA IF NOT EXISTS master1slave1;