#这个是阿里云正式环境的配置文件

#tomcat/undertow端口配置
server:
  undertow: 
    accesslog:
      dir: /data/radiation-thirdparty/logs # Undertow access log directory.     
  port: 8386
  
#日志配置
logging:
  level: 
    root: info
  file: /data/radiation-thirdparty/logs/SpringBoot.log
 
spring:
 #文件上传配置
  http:
    multipart: 
      location: /data/radiation-thirdparty/upload  # 上传文件的临时目录  
 
  #Dubbo 服务提供者配置
  dubbo:
    application: SpringBoot-provider    #提供方服务名称
    registry:
      address: zookeeper://172.16.64.75:2181   #zookeeper注册中心地址
    protocol:
      name: dubbo     #dubbo 协议
      port: 23886
    scan: cn.smarthse.business.service.dubbo #声明需要暴露的服务接口
  #数据源配置（多数据源）
  datasource:
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 校验SQL，Oracle配置 validationQuery: SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
    druid: 
      aop-patterns: cn.smarthse.business.service.*,cn.smarthse.admin.service.* # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-proxy-target-class: true
      web-stat-filter.enabled: true  #是否启用StatFilter默认值true
      stat-view-servlet.enabled: true  #是否启用StatViewServlet默认值true
  
    # 默认数据源
    url: jdbc:mysql://rm-bp1bg75tbj4cv512p.mysql.rds.aliyuncs.com:3306/db_thirdparty
    username: census_db
    password: census&*
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true


  #redis缓存配置
  redis:
     #是否启用redis缓存服务
     cacheable: false  
     #redis单机节点 JedisConnectionFactory
     host: 127.0.0.1
     port: 6379
     password: hello_redis
     pool:
         max-active: 10
         max-wait: 10
         min-idle: 1
         max-idle: 1
     #redis集群节点：RedisNode
     cluster: 
         #是否启用redis集群
         clusterable: false
         nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
         timeout: 2000
         max-redirects: 8


#ActiveMQ 配置
jms:
  #是否开启消息队列
  enable: false
  url: tcp://localhost:61616  
  queueName: darcy.queue
  topicName: darcy.topic

#web socket address, port
socket: 
  address: localhost
  port: 8080

#邮件配置
mail:
  host: hwhzsmtp.qiye.163.com
  port: 994
  username: zyj@smarthse.cn #开通了smtp服务的QQ邮箱  
  password: tR8hkLwsgkAbUZAh #授权码
  smtp:
    auth: true  
    timeout: 30000  
    starttls.enable: true
    socketFactory.port: 
  from: zyj@smarthse.cn
  replyTo: 306623095@qq.com  

#阿里云oss配置
oss:
  endpoint: http://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAIH6Jwysni9i5M
  accessKeySecret: B13HsuDlPuQvGacfKAVXH5k5C4dhgI
  bucketName: hse-oss-file1
  asynch: true #是否同步到OSS
  exptime: 3600
  publicread: true


